app:
  title: Gluo Portal - Develop
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0
    port: 3000
  hetzner:
    project:
      title: Gluo Cloud
      owner: Steven Trescinski
      lifecycle: Alpha

backend:
  baseUrl: http://localhost:7007
  listen:
    host: 0.0.0.0
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE, OPTIONS]
    credentials: true
